//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGameGeekApiClient.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardGameGeekApiClient.Tests.Resources.TestsResources", typeof(TestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;items termsofuse=&quot;http://boardgamegeek.com/xmlapi/termsofuse&quot;&gt;
        ///  &lt;item type=&quot;boardgame&quot; id=&quot;37111&quot;&gt;
        ///    &lt;thumbnail&gt;//cf.geekdo-images.com/images/pic354500_t.jpg&lt;/thumbnail&gt;
        ///    &lt;image&gt;//cf.geekdo-images.com/images/pic354500.jpg&lt;/image&gt;
        ///    &lt;name type=&quot;primary&quot; sortindex=&quot;1&quot; value=&quot;Battlestar Galactica&quot;/&gt;
        ///    &lt;name type=&quot;alternate&quot; sortindex=&quot;1&quot; value=&quot;Battlestar Galactica: Das Brettspiel&quot;/&gt;
        ///    &lt;name type=&quot;alternate&quot; sortindex=&quot;1&quot; value=&quot;Battlestar Galactica: El juego de tablero&quot;/&gt;
        ///    &lt;name type=&quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGameDetailsData {
            get {
                return ResourceManager.GetString("GetGameDetailsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;user id=&quot;473677&quot; name=&quot;TradenMyr&quot; termsofuse=&quot;http://boardgamegeek.com/xmlapi/termsofuse&quot;&gt;
        ///  &lt;firstname value=&quot;Travis&quot;/&gt;
        ///  &lt;lastname value=&quot;Merkle&quot;/&gt;
        ///  &lt;avatarlink value=&quot;//cf.geekdo-static.com/avatars/avatar_id34779.jpg&quot;/&gt;
        ///  &lt;yearregistered value=&quot;2012&quot;/&gt;
        ///  &lt;lastlogin value=&quot;2016-01-02&quot;/&gt;
        ///  &lt;stateorprovince value=&quot;&quot;/&gt;
        ///  &lt;country value=&quot;&quot;/&gt;
        ///  &lt;webaddress value=&quot;&quot;/&gt;
        ///  &lt;xboxaccount value=&quot;&quot;/&gt;
        ///  &lt;wiiaccount value=&quot;&quot;/&gt;
        ///  &lt;psnaccount value=&quot;&quot;/&gt;
        ///  &lt;battlenetaccount value=&quot;&quot;/&gt;
        ///  &lt;steamaccount value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUserDetailsData {
            get {
                return ResourceManager.GetString("GetUserDetailsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;items totalitems=&quot;16&quot; termsofuse=&quot;http://boardgamegeek.com/xmlapi/termsofuse&quot; pubdate=&quot;Sun, 24 Jan 2016 10:39:48 +0000&quot;&gt;
        ///&lt;item objecttype=&quot;thing&quot; objectid=&quot;161970&quot; subtype=&quot;boardgame&quot; collid=&quot;31122356&quot;&gt;
        ///&lt;name sortindex=&quot;1&quot;&gt;Alchemists&lt;/name&gt;
        ///&lt;yearpublished&gt;2014&lt;/yearpublished&gt;
        ///&lt;image&gt;//cf.geekdo-images.com/images/pic2241156.png&lt;/image&gt;
        ///&lt;thumbnail&gt;//cf.geekdo-images.com/images/pic2241156_t.png&lt;/thumbnail&gt;
        ///&lt;status own=&quot;1&quot; prevowned=&quot;0&quot; fortrade=&quot;0&quot; want=&quot;0&quot; wanttoplay=&quot;0&quot; wanttobuy=&quot;0&quot; wishlist=&quot;0&quot; preo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUserGamesData {
            get {
                return ResourceManager.GetString("GetUserGamesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;items total=&quot;11&quot; termsofuse=&quot;http://boardgamegeek.com/xmlapi/termsofuse&quot;&gt;
        ///  &lt;item type=&quot;boardgame&quot; id=&quot;2688&quot;&gt;
        ///    &lt;name type=&quot;primary&quot; value=&quot;Battlestar Galactica&quot;/&gt;
        ///    &lt;yearpublished value=&quot;1978&quot;/&gt;
        ///  &lt;/item&gt;
        ///  &lt;item type=&quot;boardgame&quot; id=&quot;6768&quot;&gt;
        ///    &lt;name type=&quot;primary&quot; value=&quot;Battlestar Galactica&quot;/&gt;
        ///    &lt;yearpublished value=&quot;1979&quot;/&gt;
        ///  &lt;/item&gt;
        ///  &lt;item type=&quot;boardgame&quot; id=&quot;36006&quot;&gt;
        ///    &lt;name type=&quot;primary&quot; value=&quot;Battlestar Galactica&quot;/&gt;
        ///    &lt;yearpublished value=&quot;2002&quot;/&gt;
        ///  &lt;/item&gt;
        ///  &lt;item type=&quot;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchBoardGamesData {
            get {
                return ResourceManager.GetString("SearchBoardGamesData", resourceCulture);
            }
        }
    }
}
