// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddNotesAndCreatedByApplicationUserIdToPlayedGame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNotesAndCreatedByApplicationUserIdToPlayedGame));
        
        string IMigrationMetadata.Id
        {
            get { return "201412021233106_AddNotesAndCreatedByApplicationUserIdToPlayedGame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
