// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MergeIdentityDbContextWithNemestatsAndAddGamingGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MergeIdentityDbContextWithNemestatsAndAddGamingGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201406300141380_MergeIdentityDbContextWithNemestatsAndAddGamingGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
