// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RecalculateChampionsYetAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecalculateChampionsYetAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201412102038100_RecalculateChampionsYetAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
