// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddBoardGameGeekGameDefinition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBoardGameGeekGameDefinition));
        
        string IMigrationMetadata.Id
        {
            get { return "201510260223418_AddBoardGameGeekGameDefinition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
