// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BoardGameGeekUserDefinition_FKMapping2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BoardGameGeekUserDefinition_FKMapping2));
        
        string IMigrationMetadata.Id
        {
            get { return "201601101337443_BoardGameGeekUserDefinition_FKMapping2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
