# GitHub Actions CI for NemeStats
# Windows, .NET Framework, NuGet restore, build, test (excluding Integration)

name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
